language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: Bqy2UeX7qGxImsjDoOnXVXF/v+iHBC2Y5jiWqXuO5ILNvbPwuaKySRzZ+LIzMzjgDYsssFrYpZ9hg2fO7dud+/ExgPC6lDPOV0e05l5Tpmd+MDiCq54ydjBL3H/NOiqs333d6RGYFHQoy9hPTeTIUMQEDXPr3h9pqV3xGJ3UzfXzhvXzVK1B3JhfXesoJ+bVIiop4Ji6v5hIcG5za6OVBIrVFccSZ61XzYiO0gD53NWgwcNDEhhO3Z3RQvFdSZ9LL+YqFZJVm8Nl2hqmfuerS44Pq82cAb5lWLDbjSEgcDIzas+DXTUZyiJvo3YQqwRDzrZiZQDUuEDmgek4HD1cFaqLkSPkYML2i3jiMEIVnegEPygMuung+P0K/0/QfCk7+VTI2P2TDHn7Nxhu8GyhxoYHkBS9tPvpvivtFLYHFwSfu6Cm9qqAPqjUCxk9mEQMHLFpg+rK7DkwWrzeFe3JL7QKXYf9++10lTiTMrc027DlFnzhSKxl2i3NUeVNs4c9GIwKDilkW65pMB7J5KR6nDq0SMlDZSa47TyiNHe3KDKfad/viXZVetVCkbHp8cjSICAGrLbg9UmbpkboCR2906Fej1sew9HvJFvqKJmgZonXxmR5pX9cTrz3+8wCdPBSljkx8VJlYDqCj9BtJADRIYweuomQ6gFxdIpT0hAGhQk=
  app: murmuring-escarpment-75395
